name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x, 17.x]
        operating-system: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          npm test
        env:
          CI: true
