name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [16.x]
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Test all packages
        run: pnpm test

      - name: Test all packages in server env
        run: pnpm test:ssr
