name: Update Readme

on:
  pull_request:
    types:
      - closed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.11

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: pnpm install
      - run: pnpm run update-readme

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Readme"
          file_pattern: README.md
